version: '3'
services:
  jwtdemo-api:
    image: jwtdemo/jwtdemo:latest
    restart: always

    #network_mode: host # linux host
    network_mode: bridge
    ports:
      - 8080:8080
      - 9000:9000

    environment:
      - API_PORT=8080
      - API_ACTUATOR_PORT=9000